
package MoveInvestmentService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Mon Jan 23 17:34:07 EST 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "investmentValueResponse", namespace = "http://MoveInvestmentService/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "investmentValueResponse", namespace = "http://MoveInvestmentService/")

public class InvestmentValueResponse {

    @XmlElement(name = "return")
    private model.Stock _return;

    public model.Stock getReturn() {
        return this._return;
    }

    public void setReturn(model.Stock new_return)  {
        this._return = new_return;
    }

}

